export {
    ACTION_TYPES,
    GAME_MODES,
    GAME_STATUSES,
    ADAPTATION_IDS as TRAITS,
    PLAYER_TYPES,
} from '../../shared/game-rules/types.ts'
export type {
    ActionType,
    CombatMutationEffect,
    CombatMutationId,
    CombatMutationLoadout,
    CombatMutationState,
    EnvironmentalCrisisEffect as RoundEventEffect,
    FineDelMondoActivation,
    GameMode,
    GameStatus,
    AdaptationCollection as TraitCollection,
    AdaptationId as TraitType,
    AdaptationState as TraitState,
    PlayerRoundAction,
    PlayerType,
    ResolveRoundInput,
    EnvironmentalCrisisDefinition as RoundEventDefinition,
    RoundResolution,
    RoundValueBreakdown,
    SymbiosisLink,
    SymbiosisRoundEvent,
    WorldDefinition,
} from '../../shared/game-rules/types.ts'
