const { chromium } = require('playwright-core')
    ; (async () => {
        const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, args: ['--no-sandbox'] })
        const ctx = await browser.newContext({ viewport: { width: 412, height: 924 }, deviceScaleFactor: 2 })
        const page = await ctx.newPage()
        await page.goto('http://localhost:5173/?ui-preview=battle', { waitUntil: 'networkidle' })
        await page.waitForTimeout(1000)
        await page.locator('.battle-screen').screenshot({ path: 'artifacts/preview/battle-full.png' })
        await browser.close()
    })()
