export const MUTATION_ARCHETYPES = Object.freeze([
    'LAYERED_PLATING',
    'ELASTIC_CUSHIONING',
    'SPRING_TENDONS',
    'GRIPPING_PADS',
    'BALANCE_TAIL',
    'SENSORY_FRILLS',
    'FOCUSED_OCELLI',
    'VIBRATION_FILAMENTS',
    'THERMAL_MEMBRANES',
    'GLANDULAR_RESERVOIRS',
    'VENTILATION_RIDGES',
    'HYDRODYNAMIC_WEBBING',
    'STREAMLINED_RIDGES',
    'FILTERING_FRONDS',
] as const)

export type MutationArchetype = (typeof MUTATION_ARCHETYPES)[number]
