import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { performance } from 'node:perf_hooks'
import { ROUND_EVENT_DEFINITIONS, RULE_VERSION, createLookaheadPolicy, createParametricPolicy, createSeededRandom, evaluateHeuristicAction, evolveFirstPolicy, getLegalBotActions, getRoundEventById, greedyUsePolicy, heuristicPolicy, simulateMatch, type BotDecisionContext, type BotPolicy } from '../shared/game-rules/index.ts'

type Matrix = Record<string, { count: number; observedRoundDelta: number }>
const seed = 1592598566
function seededSequences(count: number) { const ids = ROUND_EVENT_DEFINITIONS.map((event) => event.id); const random = createSeededRandom(seed); const output: string[][] = []; for (let sample = 0; sample < count; sample += 1) { const copy = [...ids]; for (let index = copy.length - 1; index > 0; index -= 1) { const swap = Math.floor(random() * (index + 1)); [copy[index], copy[swap]] = [copy[swap]!, copy[index]!] } output.push([...copy, copy[0]!]) } return output }
const actionClass = (left: { trait: string; actionType: string }, right: { trait: string; actionType: string }) => left.actionType === right.actionType && left.trait === right.trait ? 'same' : left.actionType === 'EVOLVE' && right.actionType === 'USE' ? 'EVOLVE → USE' : left.actionType === 'USE' && right.actionType === 'EVOLVE' ? 'USE → EVOLVE' : left.actionType === 'EVOLVE' ? 'EVOLVE → EVOLVE different' : 'USE → USE different'
function main() {
    const started = performance.now(); const look2 = createLookaheadPolicy({ depth: 2 }); const look3 = createLookaheadPolicy({ depth: 3 }); const opponents: BotPolicy[] = [greedyUsePolicy, createParametricPolicy({ id: 'param-matchup', useMatchup: true }), evolveFirstPolicy]; const matrix2: Matrix = {}; const matrix3: Matrix = {}; const componentTotals: Record<string, number> = {}; const examples: unknown[] = []; let decisions = 0
    for (const sequence of seededSequences(6)) for (const opponent of opponents) {
        const matchSeed = seed ^ sequence.join('|').length ^ opponent.id.length; const report = simulateMatch({ leftPolicy: heuristicPolicy, rightPolicy: opponent, eventSequence: sequence, seed: matchSeed, trace: true })
        for (const round of report.trace) {
            const next = sequence[round.roundNumber] ? getRoundEventById(sequence[round.roundNumber]!) : null; const context: BotDecisionContext = { roundNumber: round.roundNumber, ownScore: round.leftScoreBefore, opponentScore: round.rightScoreBefore, adaptations: round.leftAdaptationsBefore, publicOpponentAdaptations: round.rightAdaptationsBefore, roundEvent: round.event, nextRoundEvent: next, publicHistory: [], legalActions: getLegalBotActions(round.leftAdaptationsBefore), random: createSeededRandom(matchSeed ^ round.roundNumber) }
            const heuristic = heuristicPolicy.selectAction(context); const decision2 = look2.selectAction(context); const decision3 = look3.selectPrivilegedAction!({ ...context, remainingEvents: sequence.slice(round.roundNumber - 1).map(getRoundEventById) }); const evaluations = context.legalActions.map((action) => evaluateHeuristicAction(context, action)); for (const evaluation of evaluations) for (const [key, value] of Object.entries(evaluation.components)) componentTotals[key] = (componentTotals[key] ?? 0) + value
            const delta = round.leftValue - round.rightValue; for (const [matrix, selected] of [[matrix2, decision2], [matrix3, decision3]] as const) { const key = actionClass(heuristic, selected); const entry = matrix[key] ??= { count: 0, observedRoundDelta: 0 }; entry.count += 1; entry.observedRoundDelta += delta }
            if (examples.length < 20 && heuristic.actionType === 'EVOLVE' && decision3.actionType === 'USE') examples.push({ seed: matchSeed, events: sequence, opponent: opponent.id, round: round.roundNumber, score: `${round.leftScoreBefore}-${round.rightScoreBefore}`, heuristic, lookahead3: decision3, heuristicEvaluations: evaluations, observedRound: `${round.leftValue}-${round.rightValue}`, outcome: report.winner })
            decisions += 1
        }
    }
    const normalize = (matrix: Matrix) => Object.fromEntries(Object.entries(matrix).map(([key, value]) => [key, { frequency: value.count / decisions, ...value, averageObservedRoundDelta: value.observedRoundDelta / value.count }]))
    const payload = { ruleVersion: RULE_VERSION, seed, decisions, methodology: 'Heuristic is evaluated on states reached against deterministic greedy-use, param-matchup and evolve-first. Lookahead-3 receives remaining events only in this offline audit; this is not a simultaneous-game equilibrium.', heuristicComponentsAverage: Object.fromEntries(Object.entries(componentTotals).map(([key, value]) => [key, value / decisions])), doubleCountCheck: 'EVOLVE immediateValue is exactly EVOLVE_ROUND_VALUE; evolution is only the next-visible-event level gain. They are separate terms and not the same value counted twice.', disagreement: { lookahead2: normalize(matrix2), lookahead3: normalize(matrix3) }, examples, elapsedMs: Math.round(performance.now() - started) }
    const output = resolve(import.meta.dirname, '../artifacts/audit'); mkdirSync(output, { recursive: true }); writeFileSync(resolve(output, 'heuristic-validation.json'), `${JSON.stringify(payload, null, 2)}\n`)
    const rows = (matrix: Record<string, { frequency: number; averageObservedRoundDelta: number }>) => Object.entries(matrix).map(([key, value]) => `| ${key} | ${(value.frequency * 100).toFixed(1)}% | ${value.averageObservedRoundDelta.toFixed(2)} |`)
    const lines = ['# Heuristic validation', '', `- ${decisions} stati, ${payload.elapsedMs} ms.`, `- ${payload.doubleCountCheck}`, '', '## Heuristic vs lookahead-3', '', '| Scelta heuristic → lookahead | Frequenza | Delta round osservato |', '|---|---:|---:|', ...rows(payload.disagreement.lookahead3 as Record<string, { frequency: number; averageObservedRoundDelta: number }>), '', '## Componenti heuristic medie', '', ...Object.entries(payload.heuristicComponentsAverage).map(([key, value]) => `- ${key}: ${(value as number).toFixed(3)}`), '', `Casi heuristic=EVOLVE, lookahead=USE: ${examples.length}. Vedi JSON per seed, eventi e valutazioni per azione.`]
    writeFileSync(resolve(output, 'heuristic-validation.md'), `${lines.join('\n')}\n`); console.log(JSON.stringify({ audit: 'heuristic-validation', decisions, elapsedMs: payload.elapsedMs }))
}
main()
