import { GAME_SELECTION_ASSETS, getGeneAssetOrFallback } from './gameSelectionAssets'
import type { GeneSelectionScreenDataV2 } from './types'

export const geneSelectionMockDataV2: GeneSelectionScreenDataV2 = {
    player: {
        id: 'player-1',
        name: 'Tu',
        score: 2,
        avatarUrl: GAME_SELECTION_ASSETS.playerAvatar,
        status: 'choosing',
    },
    opponent: {
        id: 'player-2',
        name: 'Rivale',
        score: 3,
        avatarUrl: GAME_SELECTION_ASSETS.opponentAvatar,
        status: 'ready',
    },
    round: {
        current: 1,
        total: 6,
    },
    environment: {
        id: 'forest',
        name: 'Foresta fitta',
        description: 'Vegetazione densa e passaggi stretti: privilegia lettura del terreno e precisione.',
        imageUrl: GAME_SELECTION_ASSETS.environment,
        modifiers: [
            { id: 'm1', label: 'Visibilita', value: '+2 Percezione', tone: 'positive' },
            { id: 'm2', label: 'Mobilita', value: '+3 Agilita', tone: 'positive' },
            { id: 'm3', label: 'Attrito', value: '-1 Forza bruta', tone: 'negative' },
        ],
    },
    selectedAction: null,
    selectedGeneId: 'gene-agility',
    genes: [
        {
            id: 'gene-strength',
            name: 'Muscolatura compatta',
            level: 1,
            affinity: 'medium',
            imageUrl: getGeneAssetOrFallback('strength'),
            description: 'Potenza e impatto in scatti brevi.',
            predictedValue: 4,
        },
        {
            id: 'gene-resistance',
            name: 'Pelle isolante',
            level: 0,
            affinity: 'low',
            imageUrl: getGeneAssetOrFallback('resistance'),
            description: 'Stabilita in condizioni rigide.',
            predictedValue: 1,
        },
        {
            id: 'gene-agility',
            name: 'Arti elastici',
            level: 2,
            affinity: 'excellent',
            imageUrl: getGeneAssetOrFallback('agility'),
            description: 'Movimento rapido tra ostacoli naturali.',
            predictedValue: 8,
        },
        {
            id: 'gene-perception',
            name: 'Sensi acuti',
            level: 1,
            affinity: 'high',
            imageUrl: getGeneAssetOrFallback('perception'),
            description: 'Lettura veloce di minacce e percorsi.',
            predictedValue: 5,
        },
        {
            id: 'gene-metabolism',
            name: 'Respirazione efficiente',
            level: 0,
            affinity: 'low',
            imageUrl: getGeneAssetOrFallback('metabolism'),
            description: 'Gestione energia in biomi umidi.',
            predictedValue: 2,
        },
        {
            id: 'gene-adaptation',
            name: 'Plasticita biologica',
            level: 1,
            affinity: 'medium',
            imageUrl: getGeneAssetOrFallback('adaptation'),
            description: 'Compromesso versatile tra condizioni diverse.',
            predictedValue: 4,
        },
        {
            id: 'gene-grip-claws',
            name: 'Artigli prensili',
            level: 0,
            affinity: 'medium',
            imageUrl: getGeneAssetOrFallback('grip-claws'),
            description: 'Presa solida su superfici irregolari.',
            predictedValue: 3,
        },
        {
            id: 'gene-camouflage',
            name: 'Mimetismo naturale',
            level: 2,
            affinity: 'high',
            imageUrl: getGeneAssetOrFallback('camouflage'),
            description: 'Occultamento nelle aree ad alta copertura.',
            predictedValue: 7,
        },
        {
            id: 'gene-webbed-limbs',
            name: 'Arti palmati',
            level: 0,
            affinity: 'low',
            imageUrl: getGeneAssetOrFallback('webbed-limbs'),
            description: 'Mobilita su fango e tratti acquatici.',
            predictedValue: 2,
            disabled: true,
        },
        {
            id: 'gene-fat-reserves',
            name: 'Riserva adiposa',
            level: 1,
            affinity: 'medium',
            imageUrl: getGeneAssetOrFallback('fat-reserves'),
            description: 'Resistenza energetica nei round lunghi.',
            predictedValue: 4,
        },
    ],
}
