import { GAME_SELECTION_ASSETS, getGeneAssetOrFallback } from './gameSelectionAssets'
import type { GeneSelectionViewModelV2 } from './types'

export const geneSelectionMockDataV2: GeneSelectionViewModelV2 = {
    player: {
        id: 'player-1',
        name: 'Tu',
        score: 2,
        avatarUrl: GAME_SELECTION_ASSETS.playerAvatar,
        status: 'choosing',
    },
    opponent: {
        id: 'player-2',
        name: 'Rivale',
        score: 3,
        avatarUrl: GAME_SELECTION_ASSETS.opponentAvatar,
        status: 'ready',
    },
    round: {
        current: 1,
        total: 6,
    },
    environment: {
        id: 'forest',
        name: 'Foresta fitta',
        description: 'Vegetazione densa e passaggi stretti: privilegia lettura del terreno e precisione.',
        imageUrl: GAME_SELECTION_ASSETS.environment,
        modifiers: [
            { id: 'm1', label: 'Visibilita', value: '+2 Percezione', tone: 'positive' },
            { id: 'm2', label: 'Mobilita', value: '+3 Agilita', tone: 'positive' },
            { id: 'm3', label: 'Attrito', value: '-1 Forza bruta', tone: 'negative' },
        ],
    },
    status: 'choosing',
    actionsSubmitted: 0,
    selectedAction: null,
    selectedGeneId: 'AGILITY',
    genes: [
        {
            id: 'STRENGTH',
            traitType: 'STRENGTH',
            name: 'Muscolatura compatta',
            level: 1,
            affinity: 'medium',
            imageUrl: getGeneAssetOrFallback('strength'),
            description: 'Potenza e impatto in scatti brevi.',
            predictedValue: 4,
            usable: true,
        },
        {
            id: 'RESISTANCE',
            traitType: 'RESISTANCE',
            name: 'Pelle isolante',
            level: 0,
            affinity: 'low',
            imageUrl: getGeneAssetOrFallback('resistance'),
            description: 'Stabilita in condizioni rigide.',
            predictedValue: 1,
            usable: true,
        },
        {
            id: 'AGILITY',
            traitType: 'AGILITY',
            name: 'Arti elastici',
            level: 2,
            affinity: 'excellent',
            imageUrl: getGeneAssetOrFallback('agility'),
            description: 'Movimento rapido tra ostacoli naturali.',
            predictedValue: 8,
            usable: true,
        },
        {
            id: 'PERCEPTION',
            traitType: 'PERCEPTION',
            name: 'Sensi acuti',
            level: 1,
            affinity: 'high',
            imageUrl: getGeneAssetOrFallback('perception'),
            description: 'Lettura veloce di minacce e percorsi.',
            predictedValue: 5,
            usable: true,
        },
        {
            id: 'METABOLISM',
            traitType: 'METABOLISM',
            name: 'Respirazione efficiente',
            level: 0,
            affinity: 'low',
            imageUrl: getGeneAssetOrFallback('metabolism'),
            description: 'Gestione energia in biomi umidi.',
            predictedValue: 2,
            usable: true,
        },
        {
            id: 'ADAPTATION',
            traitType: 'ADAPTATION',
            name: 'Plasticita biologica',
            level: 1,
            affinity: 'medium',
            imageUrl: getGeneAssetOrFallback('adaptation'),
            description: 'Compromesso versatile tra condizioni diverse.',
            predictedValue: 4,
            usable: true,
        },
        {
            id: 'GRIP_CLAWS',
            traitType: 'GRIP_CLAWS',
            name: 'Artigli prensili',
            level: 0,
            affinity: 'medium',
            imageUrl: getGeneAssetOrFallback('grip-claws'),
            description: 'Presa solida su superfici irregolari.',
            predictedValue: 3,
            usable: true,
        },
        {
            id: 'CAMOUFLAGE',
            traitType: 'CAMOUFLAGE',
            name: 'Mimetismo naturale',
            level: 2,
            affinity: 'high',
            imageUrl: getGeneAssetOrFallback('camouflage'),
            description: 'Occultamento nelle aree ad alta copertura.',
            predictedValue: 7,
            usable: true,
        },
        {
            id: 'WEBBED_LIMBS',
            traitType: 'WEBBED_LIMBS',
            name: 'Arti palmati',
            level: 0,
            affinity: 'low',
            imageUrl: getGeneAssetOrFallback('webbed-limbs'),
            description: 'Mobilita su fango e tratti acquatici.',
            predictedValue: 2,
            usable: false,
            disabledReason: 'Cooldown 1',
        },
        {
            id: 'FAT_RESERVES',
            traitType: 'FAT_RESERVES',
            name: 'Riserva adiposa',
            level: 1,
            affinity: 'medium',
            imageUrl: getGeneAssetOrFallback('fat-reserves'),
            description: 'Resistenza energetica nei round lunghi.',
            predictedValue: 4,
            usable: true,
        },
    ],
    selectedGene: null,
    canUse: true,
    canEvolve: true,
    canSelectGenes: true,
}

geneSelectionMockDataV2.selectedGene = geneSelectionMockDataV2.genes.find((gene) => gene.id === geneSelectionMockDataV2.selectedGeneId) ?? null
